### ISSUE TITLE
heroku help showing top-level command in middle of commands

### ISSUE THREAD

**Issue by jdx** [heroku/cli-engine#133]
`ci` should be at the top:

```
$ heroku help ci
ci:config:get KEY   # get a CI config var
 ci:config           # display CI config vars
 ci:config:set       # set CI config vars
 ci:config:unset     # unset CI config vars
 ci:debug            # opens an interactive test debugging session with the
                        contents of the current directory
 ci                  # show the most recent runs
 ci:info NUMBER      # test run information
 ci:last             # get the results of the last run
 ci:migrate-manifest # app-ci.json is deprecated. Run this command to migrate
                        to app.json with an environments key.
 ci:open             # open the Dashboard version of Heroku CI
 ci:rerun [NUMBER]   # rerun tests against current directory
 ci:run              # run tests against current directory
```

**Comment by RasPhilCo** [comment]
@dickeyxxx I believe this has been addressed

**Comment by RasPhilCo** [comment]
https://github.com/heroku/cli-engine/blame/master/src/commands/help.js#L119

**Comment by jdx** [comment]
it's still showing the top-level command which I'm not sure is right.


```
$ heroku help apps
Usage: heroku apps [flags]

list your apps

Flags:
 -A, --all       include apps in all teams
 -o, --org       organization to use
 -p, --personal  list apps in personal account when a default team is set
 -s, --space     filter by space
 -t, --team      team to use
 --json          output in json format

Example:

 $ heroku apps
 === My Apps
 example
 example2

 === Collaborated Apps
 theirapp   other@owner.name

heroku apps commands: (get help with heroku help apps:COMMAND)
 apps                     list your apps
 apps:create [APP]        create a new app
 apps:destroy [APP]       permanently destroy an app
 apps:errors              view app errors
 apps:favorites           list favorited apps
 apps:favorites:add       favorites an app
 apps:favorites:remove    unfavorites an app
 apps:info [APP]          show detailed app information
 apps:join                add yourself to an organization app
 apps:lock                prevent organization members from joining an app
 apps:open [PATH]         open the app in a web browser
 apps:rename NEWNAME      rename an app
 apps:stacks              show the list of available stacks
 apps:stacks:set STACK    set the stack of an app
 apps:transfer RECIPIENT  transfer applications to another user, organization or team
```
